export const INTERCEPTOR_METADATA = 'INTERCEPTOR_METADATA';

export const NEST_HTTP_REQUEST = 'NEST_HTTP_REQUEST';
export const NEST_HTTP_REQUEST_PARAMS = 'NEST_HTTP_REQUEST_PARAMS';
export enum REQUEST_PARAM_TYPE {
  PARAM = 'PARAM',
  BODY = 'BODY',
  QUERY = 'QUERY',
  HEADER = 'HEADER',
}

export const NEST_HTTP_RESPONSE = 'NEST_HTTP_RESPONSE';
export enum NEST_HTTP_RESPONSE_CONFIG {
  FULL = 'FULL',
  HEADER = 'HEADER',
  BODY = 'BODY',
}

export const NEST_HTTP_OPTIONS_PROVIDER = 'NEST_HTTP_OPTIONS_PROVIDER';
export const AXIOS_INSTANCE_PROVIDER = 'AXIOS_INSTANCE_PROVIDER';

export const NEST_HTTP_CLIENT = 'NEST_HTTP_CLIENT';
